version: '2'
services:
  redis-server: 
    image: 'redis'
     
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    volumes: 
      - /app/node_modules
      - .:/app
